modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="layerbylayer"
version="1.0-Pre-alpha"
displayName="LBL"
authors="CrossKai"
description='''
Build reality from scratch.
Start from 0D and unlock dimensions.
'''

[[dependencies.layerbylayer]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.layerbylayer]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"